spring:
  application:
    name: turbine

server:
  port: 5001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

turbine:
  #整合的服务id
  app-config: order-service,zull
  #聚合的数据命名
  cluster-name-expression: new String("default")
