spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JacksonHoM/springcloud01.git
          search-paths: config
            #如果是私有仓库，需要用户名和密码
          default-label: main
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

server:
  port: 6001
